import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const createSidebar: any = (dir: string, name?: string) => {
  return {
    type: 'category',
    label: name || dir,
    items: [
      {type: 'autogenerated', dirName: dir},
    ],
    link: {
      type: 'generated-index'
    },
  }
};

const sidebars: SidebarsConfig = {
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  sidebar: [
    "intro",
    createSidebar('leetcode', 'LeetCode题目解析'),
    createSidebar('工程化'),
    createSidebar('CSS'),
    createSidebar('GIT'),
  ],
  sidebar2: [
    {
      type: 'category',
      label: '奇闻趣事',
      items: [
        {type: 'autogenerated', dirName: '奇闻趣事'},
      ],
      link: {
        type: 'generated-index'
      },
    }
  ]
};

export default sidebars;
